config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/home'
  get 'pages/index'
  get 'pages/about'
  get 'pages/contacto'

  root 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.html.erb
<ul class="nav navbar-nav navbar-right">
 <% if user_signed_in? %>
 <li> <a href="<%= destroy_user_session_path %>" data-method='delete'>
 Salir
 </a></li>
 <% else %>
 <li><a href="<%= new_user_session_path %>"> Login </a></li>
 <li><a href="<%= new_user_registration_path %>"> Registro </a></li>
 <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mypinterest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <%= yield %>
  </body>
</html>

app/views/pages/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="http://www.google.com">
      <span class="fab fa-phabricator text-danger" style= "color:green"></span> <b style="color:blue">HyPinterest</b>

    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
        <%=link_to "Home",root_path,class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%=link_to "About",pages_about_path,class: 'nav-link' %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>


        </li>
        <li class="nav-item">
          <%=link_to "Contacto",pages_contacto_path,class: 'nav-link' %>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>


  </nav>

app/views/pages/about.html.erb
<div class = "container">
  <div class="container">
     <div class="row">
      <h1>Loktar'Ogar</h1>
     </div>
     <div class="row">
        <button type="button" class="btn btn-primary">Pochi</button>
     </div>

  </div>


    <div class="container custom-field">
      <div class="row">
        <div class="col-md-4">
        <div class="page-header">
          <h4 style="display inline">Example page header
            <span class="badge badge-secondary">New
            </span></h4>
          <hr>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum numquam corporis minima libero optio voluptate ex porro laudantium pariatur nemo sapiente assumenda nulla, error ipsa et exercitationem velit ea! Consequatur!</p>
        </div>
        </div>
        <div class="col-md-4">
        <div class="page-header">
          <h4 style="display inline">Subtitulo
          <span class="badge badge-secondary">New
            </span></h4>
          </h4>
           <hr>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum numquam corporis minima libero optio voluptate ex porro laudantium pariatur nemo sapiente assumenda nulla, error ipsa et exercitationem velit ea! Consequatur!</p>
        </div>
        </div>
        <div class="col-md-4">
        <div class="page-header">
          <h4 style="display inline">SubSubtitulo
          <span class="badge badge-secondary">New
            </span></h4>
          </h4>
           <hr>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum numquam corporis minima libero optio voluptate ex porro laudantium pariatur nemo sapiente assumenda nulla, error ipsa et exercitationem velit ea! Consequatur!</p>
        </div>
        </div>
      </div>
    </div>
</div>

app/views/pages/contacto.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8"/>
    <title>MapCity Hello World</title>

    <script type="text/javascript" src="http://api.mapcity.com/beta/0.3.2/be0f3a14e1076fee25e5415c10539abd"></script>

    <script type="text/javascript">
    //<![CDATA[

    MapCity.Core.onReady(function() {
        var map = new MapCity.Maps.map('map');
    });

    //]]>
    </script>
    </head>
    <body>
        <div id="map" style="width: 500px; height: 300px"></div>
    </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>